spring:
  application:
    name: starship-service
server:
  port: 36795
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    homePageUrl: 'https://${eureka.instance.hostName}:${server.port}/'
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka
